### ISSUE TITLE
variables doesnt work

### ISSUE THREAD

**Issue by AlexKFU** [vphantom/gettext-pythonic#8]
Hello! if i translate my phrase without variable then all fine but else script cant find my phrase in json file. For example:

__('Hello, %{name}', {
 name: 'Alex'
});

But in json dictionary phrase == Hello, %s. And script cant find `Hello, %{name}` in dictionary and return me phrase without translate

**Comment by vphantom** [comment]
Hi!

Why does your dictionary contain `Hello, %s.` instead of `Hello, %{name}.`?

**Comment by AlexKFU** [comment]
@vphantom, po2json generate me this json... In .po file i have `Hello, %s`. And po2json generate this string. Thank you for answer!

**Comment by vphantom** [comment]
Ah ha!  Now I understand what you mean. :)  As hinted in [Variable substitution](https://github.com/vphantom/gettext-pythonic#variable-substitution) in the README, my choice to use "pythonic string formatting" instead of sprintf() style formatting means that your PO file must use the numbered or named variables, not `%s` type placeholders.  So in your example, your PO file should contain `Hello, %{name}.` because `%s` is not understood by gettext-pythonic.

**Comment by vphantom** [comment]
(Sorry, I edited the above: I meant of course `Hello, %{name}.` for my PO example. That `$` was a typo.)

**Comment by AlexKFU** [comment]
@vphantom, do you mean that i should store string in .po like this `Hello, %{name}`.
And in js i should write like this `__('Hello, %{name}', {name: 'Alex'})`? Thank you very much for help!

**Comment by vphantom** [comment]
Yes indeed.  Your JavaScript was correct, so you just need to update your PO file to use the new style of placeholders. :)

**Comment by AlexKFU** [comment]
Thank you very much!:)
